version: '3.8'

services:
  db:
    image: mysql:latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: mosun_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
  app:
    depends_on:
      - db
    build:
      dockerfile: dockerfile
      context: .
    volumes:
      - ./app_data:/var/www/html
    ports:
      - 3000:3000
